apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-app
  namespace: dashboard-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard-app
  template:
    metadata:
      labels:
        app: dashboard-app
    spec:
      serviceAccountName: dashboard-app-sa
      containers:
        - name: dashboard-app
          image: dashboard-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"