apiVersion: v1
kind: Service
metadata:
  name: dashboard-app-service
  namespace: dashboard-app
spec:
  selector:
    app: dashboard-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000